name: Deploy
on:
  push:
    branches:
      - master

concurrency:
  group: "nsite"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./dist

      - name: Deploy nsite
        run: npx -y nsite-cli upload anarplex.sirion.io --verbose --purge --privatekey ${{ secrets.NSITE_KEY }}
